# I feel like I have the responeability to tell 
# you that all of the dbus_mpris.py file 
# has been generated by AI 
# the rest of the project has not tho 
# feel free not not use this part or reimplement 
# it without AI
import asyncio
import hashlib
from pathlib import Path
import threading

import pygame
from dbus_next import Variant
from dbus_next.aio import MessageBus
from dbus_next.constants import PropertyAccess
from dbus_next.service import ServiceInterface, dbus_property, method


BUS_NAME = "org.mpris.MediaPlayer2.myplayer"
OBJECT_PATH = "/org/mpris/MediaPlayer2"


# ======================================================================
# org.mpris.MediaPlayer2
# ======================================================================

class MediaPlayer2(ServiceInterface):
    def __init__(self):
        super().__init__("org.mpris.MediaPlayer2")

    @dbus_property(access=PropertyAccess.READ)
    def Identity(self) -> "s":
        return "myplayer"

    @dbus_property(access=PropertyAccess.READ)
    def DesktopEntry(self) -> "s":
        return "myplayer"

    @dbus_property(access=PropertyAccess.READ)
    def CanQuit(self) -> "b":
        return False

    @dbus_property(access=PropertyAccess.READ)
    def CanRaise(self) -> "b":
        return False

    @dbus_property(access=PropertyAccess.READ)
    def HasTrackList(self) -> "b":
        return False

    @dbus_property(access=PropertyAccess.READ)
    def Fullscreen(self) -> "b":
        return False

    @dbus_property(access=PropertyAccess.READ)
    def CanSetFullscreen(self) -> "b":
        return False

    @dbus_property(access=PropertyAccess.READ)
    def SupportedUriSchemes(self) -> "as":
        return ["file"]

    @dbus_property(access=PropertyAccess.READ)
    def SupportedMimeTypes(self) -> "as":
        return [
            "audio/mpeg",
            "audio/ogg",
            "audio/wav",
            "audio/flac",
        ]

    @method()
    def Raise(self):
        pass

    @method()
    def Quit(self):
        pass


# ======================================================================
# org.mpris.MediaPlayer2.Player
# ======================================================================

class MediaPlayer2Player(ServiceInterface):
    def __init__(self, player):
        super().__init__("org.mpris.MediaPlayer2.Player")

        self.player = player

        # MPRIS-owned shuffle state.
        #
        # IMPORTANT:
        # This getter must NEVER call shuffled_playlist().
        self._shuffle = False

        self._last_status = None
        self._last_volume = None
        self._last_track_id = None

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _status(self):
        # Your Player semantics:
        #
        # running=True  -> application is alive
        # song_is_paused=True -> playback is paused
        #
        # We therefore derive MPRIS state from both.
        if not self.player.running:
            return "Stopped"

        if self.player.song_is_paused:
            return "Paused"

        return "Playing"

    def _position_us(self):
        return int(
            float(self.player.song_seconds) * 1_000_000
        )

    def _current_file(self):
        return Path(
            self.player.playlist.current.file_path
        ).resolve()

    def _track_id(self):
        """
        Generate a valid, stable D-Bus object path.

        Hashing the filename avoids illegal object-path characters.
        """
        path = str(self._current_file())

        digest = hashlib.sha1(
            path.encode("utf-8", errors="surrogatepass")
        ).hexdigest()

        return (
            "/org/mpris/MediaPlayer2/track/"
            + digest
        )

    def _file_uri(self):
        return self._current_file().as_uri()

    def _metadata(self):
        song = self.player.playlist.current

        metadata = {
            "mpris:trackid": Variant(
                "o",
                self._track_id(),
            ),

            "xesam:url": Variant(
                "s",
                self._file_uri(),
            ),
        }

        # Your provided Player definitely has .name.
        title = getattr(song, "name", None)

        if title:
            metadata["xesam:title"] = Variant(
                "s",
                str(title),
            )

        # Support these automatically if your Song object provides them.
        artist = getattr(song, "artist", None)
        if artist:
            metadata["xesam:artist"] = Variant(
                "as",
                [str(artist)],
            )

        album = getattr(song, "album", None)
        if album:
            metadata["xesam:album"] = Variant(
                "s",
                str(album),
            )

        album_artist = getattr(song, "album_artist", None)
        if album_artist:
            metadata["xesam:albumArtist"] = Variant(
                "s",
                str(album_artist),
            )

        genre = getattr(song, "genre", None)
        if genre:
            metadata["xesam:genre"] = Variant(
                "as",
                [str(genre)],
            )

        # Player already calculates this.
        if getattr(self.player, "song_length", None) is not None:
            metadata["mpris:length"] = Variant(
                "x",
                int(
                    float(self.player.song_length)
                    * 1_000_000
                ),
            )

        return metadata

    # ------------------------------------------------------------------
    # MPRIS properties
    # ------------------------------------------------------------------

    @dbus_property(access=PropertyAccess.READ)
    def PlaybackStatus(self) -> "s":
        return self._status()

    @dbus_property(access=PropertyAccess.READWRITE)
    def LoopStatus(self) -> "s":
        return "None"

    @LoopStatus.setter
    def LoopStatus(self, value: "s"):
        # Looping is not implemented by the Player.
        if value not in ("None", "Track", "Playlist"):
            raise ValueError(
                f"Invalid LoopStatus: {value}"
            )

    @dbus_property(access=PropertyAccess.READWRITE)
    def Rate(self) -> "d":
        return 1.0

    @Rate.setter
    def Rate(self, value: "d"):
        if float(value) != 1.0:
            raise ValueError(
                "Variable playback rate is not supported"
            )

    @dbus_property(access=PropertyAccess.READWRITE)
    def Shuffle(self) -> "b":
        # DO NOT DO THIS:
        #
        # return self.player.shuffled_playlist()
        #
        # i3status-rust reads properties, and a getter must not
        # change the playlist.
        return self._shuffle

    @Shuffle.setter
    def Shuffle(self, value: "b"):
        value = bool(value)

        if value == self._shuffle:
            return

        self._shuffle = value

        if value:
            self.player.shuffled_playlist()

        self.emit_properties_changed({
            "Shuffle": self._shuffle,
        })

    @dbus_property(access=PropertyAccess.READ)
    def Metadata(self) -> "a{sv}":
        return self._metadata()

    @dbus_property(access=PropertyAccess.READWRITE)
    def Volume(self) -> "d":
        return float(self.player.volume)

    @Volume.setter
    def Volume(self, value: "d"):
        self.player.set_volume(
            value=float(value)
        )

        self.emit_properties_changed({
            "Volume": float(self.player.volume),
        })

    @dbus_property(access=PropertyAccess.READ)
    def Position(self) -> "x":
        return self._position_us()

    @dbus_property(access=PropertyAccess.READ)
    def MinimumRate(self) -> "d":
        return 1.0

    @dbus_property(access=PropertyAccess.READ)
    def MaximumRate(self) -> "d":
        return 1.0

    @dbus_property(access=PropertyAccess.READ)
    def CanGoNext(self) -> "b":
        return True

    @dbus_property(access=PropertyAccess.READ)
    def CanGoPrevious(self) -> "b":
        return True

    @dbus_property(access=PropertyAccess.READ)
    def CanPlay(self) -> "b":
        return True

    @dbus_property(access=PropertyAccess.READ)
    def CanPause(self) -> "b":
        return True

    @dbus_property(access=PropertyAccess.READ)
    def CanSeek(self) -> "b":
        return True

    @dbus_property(access=PropertyAccess.READ)
    def CanControl(self) -> "b":
        return True

    # ------------------------------------------------------------------
    # Playback methods
    # ------------------------------------------------------------------

    @method()
    def Play(self):
        print("MPRIS: Play", flush=True)

        # Your Player.play() already has the intended semantics.
        self.player.play()

        self._emit_status()

    @method()
    def Pause(self):
        print("MPRIS: Pause", flush=True)

        # Your Player.stop() intentionally means pause.
        self.player.stop()

        self._emit_status()

    @method()
    def PlayPause(self):
        print("MPRIS: PlayPause", flush=True)

        self.player.playpause()

        self._emit_status()

    @method()
    def Stop(self):
        print("MPRIS: Stop", flush=True)

        # Keep your Player semantics unchanged.
        self.player.stop()

        self._emit_status()

    @method()
    def Next(self):
        print("MPRIS: Next", flush=True)

        self.player.start_next_song()

        self._emit_track()

    @method()
    def Previous(self):
        print("MPRIS: Previous", flush=True)

        self.player.start_previous_song()

        self._emit_track()

    # ------------------------------------------------------------------
    # Seeking
    # ------------------------------------------------------------------

    @method()
    def Seek(self, offset: "x"):
        """
        MPRIS offset is microseconds.

        Your Player already uses pygame.mixer.music.set_pos()
        internally, so use the same thing here.
        """
        offset_seconds = float(offset) / 1_000_000

        new_position = (
            self.player.song_seconds
            + offset_seconds
        )

        new_position = max(
            0,
            min(
                self.player.song_length,
                new_position,
            ),
        )

        pygame.mixer.music.set_pos(
            new_position
        )

        self.player.song_seconds = new_position

        self.emit_properties_changed({
            "Position": self._position_us(),
        })

    @method()
    def SetPosition(
        self,
        track_id: "o",
        position: "x",
    ):
        """
        Set absolute playback position.

        Ignore track_id unless it refers to our current track.
        """
        if track_id != self._track_id():
            return

        position_seconds = (
            float(position) / 1_000_000
        )

        position_seconds = max(
            0,
            min(
                self.player.song_length,
                position_seconds,
            ),
        )

        pygame.mixer.music.set_pos(
            position_seconds
        )

        self.player.song_seconds = position_seconds

        self.emit_properties_changed({
            "Position": self._position_us(),
        })

    # ------------------------------------------------------------------
    # Change notifications
    # ------------------------------------------------------------------

    def _emit_status(self):
        status = self._status()

        self._last_status = status

        self.emit_properties_changed({
            "PlaybackStatus": status,
        })

    def _emit_track(self):
        track_id = self._track_id()

        self._last_track_id = track_id

        self.emit_properties_changed({
            "Metadata": self._metadata(),
            "Position": self._position_us(),
        })

        self._emit_status()

    def poll(self):
        """
        Detect changes made by the curses UI / Player itself.

        This means i3status-rust stays updated when you use:

            Space
            <
            >
            Up
            Down
            s
        """

        try:
            status = self._status()

            if status != self._last_status:
                self._last_status = status

                self.emit_properties_changed({
                    "PlaybackStatus": status,
                })

            volume = float(self.player.volume)

            if volume != self._last_volume:
                self._last_volume = volume

                self.emit_properties_changed({
                    "Volume": volume,
                })

            track_id = self._track_id()

            if track_id != self._last_track_id:
                self._last_track_id = track_id

                self.emit_properties_changed({
                    "Metadata": self._metadata(),
                    "Position": self._position_us(),
                })

        except Exception as exc:
            print(
                f"MPRIS poll error: {exc}",
                flush=True,
            )


# ======================================================================
# Start MPRIS service
# ======================================================================

def mpris_dbus_start(player):

    async def dbus_main():
        try:
            bus = await MessageBus().connect()

            print(
                "MPRIS: connected to session bus",
                flush=True,
            )

            reply = await bus.request_name(BUS_NAME)

            print(
                f"MPRIS: request_name -> {reply}",
                flush=True,
            )

            root = MediaPlayer2()
            mpris_player = MediaPlayer2Player(player)

            bus.export(
                OBJECT_PATH,
                root,
            )

            bus.export(
                OBJECT_PATH,
                mpris_player,
            )

            # Initial cache.
            mpris_player._last_status = (
                mpris_player._status()
            )

            mpris_player._last_volume = (
                float(player.volume)
            )

            mpris_player._last_track_id = (
                mpris_player._track_id()
            )

            print(
                f"MPRIS: running as {BUS_NAME}",
                flush=True,
            )

            print(
                f"MPRIS: object {OBJECT_PATH}",
                flush=True,
            )

            while True:
                await asyncio.sleep(0.1)
                mpris_player.poll()

        except Exception:
            import traceback

            print(
                "MPRIS: fatal error",
                flush=True,
            )

            traceback.print_exc()

    def dbus_thread():
        asyncio.run(dbus_main())

    thread = threading.Thread(
        target=dbus_thread,
        name="mpris-dbus",
        daemon=True,
    )

    thread.start()

    return thread
